package hu.qiang.filezip;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import hu.qiang.filezip.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    }
}
