package hu.qiang.filezip;

import java.io.IOException;
import java.security.InvalidParameterException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private static final Logger logger = LoggerFactory.getLogger(App.class);

	public static void main(String[] args) {
		FileZip fz = new FileZip();
		if (args[0].equals("compression")) {
			if (args.length != 4) {
				throw new InvalidParameterException("This program takes 4 inputs.");
			}
			fz.compressDirectory(args[1], args[2], Integer.valueOf(args[3]));
		} else if (args[0].equals("decompression")) {
			if (args.length != 3) {
				throw new InvalidParameterException("This program takes 3 inputs.");
			}
			try {
				fz.decompressDirectory(args[1], args[2]);
			} catch (IOException e) {
				logger.error("Fail to decompress directory: " + args[0] + " - " + e.getMessage(), e);
			}
		}
	}
}
