package hu.qiang.filezip;
import java.security.InvalidParameterException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		if (args[0].equals("compression")) {
			if (args.length != 3) {
				throw new InvalidParameterException("This program takes 3 inputs.");
			}
		}else if (args[0].equals("decompression")) {
			if (args.length != 2) {
				throw new InvalidParameterException("This program takes 3 inputs.");
			}
		}
	}
}
